/**
 * Script ad-hoc pra aplicar fix do bug de blueprints duplicados
 * descoberto no Playwright test 2026-04-21.
 *
 * 1. Apaga blueprints duplicados (mantém APPROVED, senão o mais recente)
 * 2. Aplica UNIQUE constraint (sessionId, type) em agent_artifact
 * 3. Cleanup: reindex
 *
 * Run: pnpm -w exec tsx scripts/fix-artifact-dedup.ts
 */
import { agentArtifact, db, sql } from "@repo/database";

async function main() {
	console.log("[fix] Starting artifact dedup + unique constraint");

	// Step 1: Identify duplicates
	const dupes = await db.execute(sql`
		SELECT "sessionId", "type", COUNT(*) as cnt
		FROM agent_artifact
		GROUP BY "sessionId", "type"
		HAVING COUNT(*) > 1
	`);
	console.log(`[fix] Found ${dupes.rows.length} duplicate groups`);

	// Step 2: For each duplicate group, keep best artifact (APPROVED > REGENERATED > GENERATED by updatedAt DESC)
	for (const row of dupes.rows as Array<{ sessionId: string; type: string; cnt: number }>) {
		const artifacts = await db.execute(sql`
			SELECT id, status, version, "updatedAt"
			FROM agent_artifact
			WHERE "sessionId" = ${row.sessionId} AND "type" = ${row.type}
			ORDER BY
				CASE status
					WHEN 'APPROVED' THEN 1
					WHEN 'REGENERATED' THEN 2
					WHEN 'GENERATED' THEN 3
				END ASC,
				version DESC,
				"updatedAt" DESC
		`);
		const keep = artifacts.rows[0] as { id: string; status: string };
		const deleteIds = (artifacts.rows as Array<{ id: string }>).slice(1).map((r) => r.id);
		console.log(`[fix] sessionId=${row.sessionId} type=${row.type}: keep ${keep.id} (${keep.status}), delete ${deleteIds.length}`);
		for (const delId of deleteIds) {
			await db.execute(sql`DELETE FROM agent_artifact WHERE id = ${delId}`);
		}
	}

	// Step 3: Drop old non-unique index, create unique index
	console.log("[fix] Dropping old index + adding unique constraint");
	await db.execute(sql`DROP INDEX IF EXISTS agent_artifact_session_type_idx`);
	await db.execute(sql`
		CREATE UNIQUE INDEX IF NOT EXISTS agent_artifact_session_type_unique
		ON agent_artifact ("sessionId", "type")
	`);

	console.log("[fix] Done");
	process.exit(0);
}

main().catch((err) => {
	console.error("[fix] Failed", err);
	process.exit(1);
});
